Meteor.methods
  "grid_createFile": (filename, length, meta={}) ->
    FileGrid.createFile arguments...
  "grid_setChunk": (files_id, n, data) ->
    @unblock()
    FileGrid.setChunk arguments...
  "grid_getChunk": (files_id, n) ->
    @unblock()
    FileGrid.getChunk arguments...
  "grid_finalize": (files_id) ->
    FileGrid.finalize arguments...
  "grid_deleteFile": (files_id) ->
    FileGrid.deleteFile arguments...
